version: '3.5'

services:
  postgresql_messagingapi_db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=messaging_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      my_network:
        ipv4_address: 10.10.0.2

  messagingapi_app:
    image: "messaging_api:latest"
    depends_on:
      - postgresql_messagingapi_db
    external_links:
      - postgresql_messagingapi_db:psql
    ports:
      - "80:4000"
    environment:
      - HOSTNAME=localhost
      - SECRET_KEY_BASE="u1QXlca4XEZKb1o3HL/aUlznI1qstCNAQ6yme/lFbFIs0Iqiq/annZ+Ty8JyUCDc"
      - DATABASE_HOST=psql
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_NAME=messaging_api_db
      - PORT=4000
      - LANG=en_US.UTF-8
      - REPLACE_OS_VARS=true
      - ERLANG_COOKIE=messaging_api
    networks:
      my_network:
        ipv4_address: 10.10.0.3


networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24